### ISSUE TITLE
Version 4.0 Release Checklist

### ISSUE THREAD

**Issue by AjaniBilby** [AjaniBilby/BNF-parser#12]
- [x] All issues related to release closed
- [x] Documentation
  - [x] CLI usage
  - [x] Shared Artifact API outline
  - [x] Bnf artifact API outline
  - [x] Whole library API outline
